### ISSUE TITLE
Make it GNOME Shell compatible

### ISSUE THREAD

**Issue by jonnius** [sneetsher/indicator-xkbmod#4]
Could you port this Indicator to work with GNOME Shell, please? E.g. as an Extension or by making it possible to wirk with App Indicator Support on GNOME Shell: https://extensions.gnome.org/extension/615/appindicator-support/. Using labels (/usr/bin/indicator-xkbmod -l) already works this way. (Could be default on GNOME Shell).

**Comment by sneetsher** [comment]
Thank you @jonnius for this report. I thought about this before but I just wait to see if gnome team will make one. This is a core accessibility feature. Now, years passed with gnome shell, no light yet.

I will give it some time to test using `appindicator-support`, it seems to me a quick track, at least it can be used.

If I have some some spare time, I will try writing native one. I'm just struggling with the new Gnome JS.

**Comment by sneetsher** [comment]
I've added a new desktop file for Gnome which launch it with `-l` label option.

I have read this https://github.com/rgcjonas/gnome-shell-extension-appindicator/issues/56 . I hope it stay working till I got a solution with native code.

Thank you again @jonnius

**Comment by sneetsher** [comment]
I just uploaded a native Gnome Shell extension. @jonnius & @overthetop, Would please try it.

Could be installed from: https://extensions.gnome.org/extension/975/keyboard-modifiers-status/

Please report issue in its separate repo: https://github.com/sneetsher/Keyboard-Modifiers-Status

**Comment by jonnius** [comment]
It works fine on GS 3.16 (just needed to add the version tag). See PR https://github.com/sneetsher/Keyboard-Modifiers-Status/pull/1
Thanks!

**Comment by overthetop** [comment]
@sneetsher thx man :) works great!
