### ISSUE TITLE
I can't see the indicator on my Debian 8 machine

### ISSUE THREAD

**Issue by overthetop** [sneetsher/indicator-xkbmod#5]
Please add support for gnome desktop. It's a shame to have such a great tool and be available only for Ubuntu!

**Comment by sneetsher** [comment]
Thank you @overthetop . This is same feature requested in issue / duplicate #4  to make it gnome shell compatible. Please could you follow that report for updates. If you have any additional comment leave it there.

**Comment by jonnius** [comment]
As i wrote in #4 you can use AppIndicator Extension and start this indicator with labels using '/usr/bin/indicator-xkbmod -l'
