### ISSUE TITLE
Applet does not show state of modifier keys.

### ISSUE THREAD

**Issue by dotancohen** [sneetsher/indicator-xkbmod#6]
Though the applet runs fine and displays an interface in the Unity panel, it does not respond to changes in the state of the keys. However, the C code compiled from this AskUbuntu answer does work properly and I use it daily:
http://askubuntu.com/questions/402315/how-to-add-a-keyboard-modifier-state-applet-to-unity-panel

This is my system:

```
$ uname -a
Linux dotan-tm 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 15.10 \n \l
```

This is the package that I used:
http://ppa.launchpad.net/sneetsher/one/ubuntu/pool/main/i/indicator-xkbmod/indicator-xkbmod_0.1-0~37~ubuntu15.10.1_amd64.deb

**Comment by dotancohen** [comment]
For unrelated reasons I have reset the machine with indicator-xkbmod installed. Now the applet works properly. For some reason, logging out and then logging back in after installation did not result in a working plugin, but a restart did.

Thank you!

**Comment by sneetsher** [comment]
Thank you @dotancohen for reporting this and nice that you got to work. This will help other users. 

I will try it in fresh Ubuntu installation to see if I can make it run correctly without reboot.

**Comment by 01peter** [comment]
Salamu alaykum akhi Abdulla

i sent you an mail, is it possible for you to check it? or maybe PM me though github. im not sure how to do so.  @sneetsher
